services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env.local
    volumes:
      - .local-secrets:/secrets
      - db-data:/app/persistence
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend/.env.local:/app/.env.local
      - .local-secrets:/secrets
      - db-data-frontend:/app/persistence
    ports:
      - 3000:3000

volumes:
  db-data:
  db-data-frontend:
