# yaml-language-server: $schema=../../infra-helm-charts/charts/generic-app/values.schema.json
environment: "prod"
version: "${COMMIT_SHA}"
deployments:
  - name: "macroservices-backend"
    image: "${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${REPO_NAME}-backend"
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      I18N_NEXUS_API_KEY: "/secrets/i18n-nexus-api-key"
    secrets:
      i18n-nexus-api-key: "${I18N_NEXUS_API_KEY}"
    service:
      port: 8000
    ingress:
      subdomain: "macroservices"
    readinessProbe:
      httpGet:
        port: 8000
        path: "/api/v3/healthcheck"
    volumes:
      - name: "backend-data"
        mountPath: "/app/persistence"
        size: "1Gi"

  - name: "macroservices-frontend"
    image: "${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${REPO_NAME}-frontend"
    config:
      fileVariable: "frontendEnvConfig"
      fileName: ".env"
      mountPath: "/app/.env"
      subPath: ".env"
    service:
      port: 3000
    ingress:
      subdomain: "app-macroservices"
    readinessProbe:
      httpGet:
        port: 3000
        path: /
    volumes:
      - name: "frontend-data"
        mountPath: "/app/persistence"
        size: "1Gi"
